name: Maven Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # docker login
    # - name: Docker login
    #   run: docker login -u "applepie2" - p "helloworlD@8"

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Create Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: applepie2/repo2:image2
      # env:
      #   DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      #   DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Build
      run: docker build -t applepie2/myimage:latest .
        
