name: Maven Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create Docker image
      uses: docker/build-push-actions@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: applepie2/myrepo:myimage
